//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinancialTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string CategoryType { get; set; }
        public string Income { get; set; }
        public string Expense { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string Amount { get; set; }
        public string EventType { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Category Category { get; set; }
    }
}
