//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinancialTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string CategoryType { get; set; }
        public string Income { get; set; }
        public string Expense { get; set; }
        public string TransactionDescription { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Amount { get; set; }
        public string EventName { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> EventId { get; set; }
    }
}
